apiVersion: v2
name: msr
type: application
version: 4.0.1
dependencies:
  - name: harbor
    version: 4.0.1
    repository: https://registry.mirantis.com/charts/harbor/helm
  - name: ingress-nginx
    version: 4.12.0
    repository: https://kubernetes.github.io/ingress-nginx
